version: '3'
services:
  db:
    container_name: ServerMySQL
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: authFiles
      MYSQL_USER: denis
      MYSQL_PASSWORD: 54321
      TZ: Europe/Bucharest
    volumes:
      - databaseSQL:/var/lib/mysql
      #  creeaza baza de date prin fisierul cu extensia .mysql din folderul local ./database
      # - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s
    networks:
      - mariadb_network
    ports:
      - "3307:3306"

  flask_app:
    container_name: DatasetsFactory
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mariadb_network
      - nginx_network
    ports:
      - "8000:8000"
    command: bash -c 'gunicorn --bind 0.0.0.0:8000 "wsgi:app_gunicorn"'

  nginx:
    image: nginx
    container_name: flask_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask_app
    networks:
      - nginx_network

volumes:
  databaseSQL:
networks:
  mariadb_network:
  nginx_network:
