"""Am schimbat tipul de date pentru size in data_files!

Revision ID: 624714d919ee
Revises: 84e334e0635a
Create Date: 2024-05-21 23:41:07.633243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '624714d919ee'
down_revision = '84e334e0635a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_files', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
