"""Am adaugat TokenKey column la user_identification ca sa urmaresc cine face load la dataset!

Revision ID: fb308a48e829
Revises: 
Create Date: 2024-05-21 21:23:18.191929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb308a48e829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TokenKey', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identification', schema=None) as batch_op:
        batch_op.drop_column('TokenKey')

    # ### end Alembic commands ###
